version: '2'
services:
  f1db:
    image: registry.gitlab.com/chauffer/f1analytics/postgres
  postgres:
    image: postgres:10-alpine
    volumes:
     - ./pgdata:/var/lib/postgresql/data
  metabase:
    image: metabase/metabase:v0.30.0
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: postgres
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: postgres
    ports:
      - 3000
